storage:
  method: h2 # h2 (local) or mysql (online)
  mysql:
    host: localhost
    port: 104
    database: thisisamysqldatabase
    user: thisisamysqlusername
    password: thisisastrongpassword

economy:
  currency: "$"

placeholder_format: "%balance% %currency%" # No color codes here.

messages:

  errors:
    invalid_arguments: "&7[&3S&bE&7] &cInvalid Arguments. Run /seco help for a list of commands."
    player_not_found: "&7[&3S&bE&7] &cPlayer not found."
    account_not_found: "&7[&3S&bE&7] &cAccount not found."
    invalid_amount: "&7[&3S&bE&7] &cInvalid amount."
    only_players: "&7[&3S&bE&7] &cOnly players can use this command."
    pay_self: "&7[&3S&bE&7] &cYou cannot pay yourself."
    insufficient_funds: "&7[&3S&bE&7] &cInsufficient funds."
    minimum_amount: "&7[&3S&bE&7] &cMinimum amount is %amount%."

  pay:
    success: "&7[&3S&bE&7] &aYou have paid &b%player% &b%currency%%amount%."
    received: "&7[&3S&bE&7] &b%player% &fhas paid you &b%currency%%amount%."

  balance: "&7[&3S&bE&7] &fYour Balance: &b%currency%%balance%&f."

  account:
    info:
      - ""
      - "&7[&3S&bE&7] &fAccount Information:"
      - "&7- &fOwner: &b%name%"
      - "&7- &fBalance: &b%currency%%balance%"
      - ""
    balance:
      admin:
        set: "&7[&3S&bE&7] &8Set &b%player%&f's balance to &b%currency%%amount%&f."
        add: "&7[&3S&bE&7] &aAdded &b%currency%%amount% &fto &b%player%&f's balance."
        remove: "&7[&3S&bE&7] &cRemoved &b%currency%%amount% &ffrom &b%player%&f's balance."
      target:
        set: "&7[&3S&bE&7] &fYour balance has been set to &b%currency%%amount%&f."
        add: "&7[&3S&bE&7] &f&b%currency%%amount% &fhas been &aadded &fto your account."
        remove: "&7[&3S&bE&7] &f&b%currency%%amount% &fhave been &cremoved &ffrom your account."

    delete: "&7[&3S&bE&7] &f&b%player%&f's account has been deleted."

    unload: "&7[&3S&bE&7] &f&b%player%&f's account has been unloaded."