name: SpectralEconomy
version: '1.0'
main: dev.vulpine.spectralEconomy.SpectralEconomy

depend:
  - PlaceholderAPI

commands:
  spectraleconomy:
    aliases: [se, seco, seconomy]

  balance:
    aliases: [bal]

  pay: